[default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 2000
via_ir = true
bytecode_hash = "ipfs"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
